name: iceflow
channels:
  - conda-forge
  - nsidc
dependencies:
  - python ~=3.12.0
  - earthaccess ~=0.10.0
  - pandas
  - h5py
  - numpy
  - gps-timemachine
  - pyproj
  - shapely
  # dev tools
  - pre-commit
  - invoke
  - mypy
  - pytest
